# golangci-lint configuration for obsidian-notion-sync
# golangci-lint v2 format
# See: https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    # Code quality
    - misspell
    - unconvert
    # Disabled until existing issues are fixed:
    # - goconst  # TODO: Fix repeated strings
    # - dupl     # TODO: Refactor duplicate code
    # Security (relaxed for now)
    # - gosec    # TODO: Fix file permission warnings
    # Performance
    # - prealloc # TODO: Pre-allocate slices

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

    govet:
      disable:
        - fieldalignment

    staticcheck:
      checks:
        - all
        - -SA1019

    gosec:
      excludes:
        - G104
        - G304

    misspell:
      locale: US

    goconst:
      min-len: 3
      min-occurrences: 3

    dupl:
      threshold: 150

  exclusions:
    presets:
      - std-error-handling
    rules:
      # Exclude test files from strict linting
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - errcheck
          - goconst
          - staticcheck

      # Allow unchecked tx.Rollback (common pattern in deferred calls)
      - text: "Error return value of `tx.Rollback` is not checked"
        linters:
          - errcheck

      # Allow unchecked yaml.Unmarshal in best-effort parsing
      - text: "Error return value of `yaml.Unmarshal` is not checked"
        linters:
          - errcheck

      # Allow 0644 file permissions for user-accessible files
      - text: "G306:"
        linters:
          - gosec

      - text: "G302:"
        linters:
          - gosec

      - text: "G301:"
        linters:
          - gosec

      # Staticcheck exclusions for existing code patterns
      - text: "ST1003:"
        linters:
          - staticcheck

      - text: "ST1016:"
        linters:
          - staticcheck

      - text: "ST1021:"
        linters:
          - staticcheck

      - text: "QF1001:"
        linters:
          - staticcheck

      - text: "QF1008:"
        linters:
          - staticcheck

      - text: "QF1012:"
        linters:
          - staticcheck

      - text: "S1009:"
        linters:
          - staticcheck

      - text: "SA4011:"
        linters:
          - staticcheck

      - text: "SA5011:"
        linters:
          - staticcheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
